/**
 * Vendors the two theme-licensed families into `public/fonts/` so builds never depend
 * on a live Google Fonts request (a Docker build behind a restrictive network would
 * otherwise fail, and a CDN font would be a third-party request on every page view).
 *
 *   Vazirmatn — OFL, Persian UI fallback (variable, wght 100..900), arabic + latin
 *   Inter     — OFL, English UI (variable, wght 100..900), latin
 *
 * Run: npm run fonts   (idempotent; re-downloads and rewrites provenance)
 */
import { mkdir, writeFile } from 'node:fs/promises'
import { join } from 'node:path'

const OUT = join(process.cwd(), 'public', 'fonts')
const UA =
  'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0 Safari/537.36'

const targets = [
  {
    family: 'Vazirmatn',
    css: 'https://fonts.googleapis.com/css2?family=Vazirmatn:wght@100..900&display=swap',
    wanted: ['arabic', 'latin'],
    prefix: 'vazirmatn',
  },
  {
    family: 'Inter',
    css: 'https://fonts.googleapis.com/css2?family=Inter:wght@100..900&display=swap',
    wanted: ['latin'],
    prefix: 'inter',
  },
]

/** Pull `/* subset *\/ … url(…)` pairs out of the css2 response. */
const parse = (css) => {
  const blocks = css.split('/*').slice(1)
  return blocks
    .map((block) => {
      const subset = block.slice(0, block.indexOf('*/')).trim()
      const url = block.match(/url\((https:\/\/[^)]+\.woff2)\)/)?.[1]
      const unicodeRange = block.match(/unicode-range:\s*([^;]+);/)?.[1]?.trim()
      return url ? { subset, unicodeRange, url } : null
    })
    .filter(Boolean)
}

await mkdir(OUT, { recursive: true })
const provenance = ['Vendored webfonts — generated by `npm run fonts`', '']

for (const target of targets) {
  const css = await fetch(target.css, { headers: { 'user-agent': UA } }).then((r) => r.text())
  const files = parse(css).filter((f) => target.wanted.includes(f.subset))
  if (!files.length) throw new Error(`no woff2 subsets found for ${target.family}`)
  for (const file of files) {
    const bytes = Buffer.from(await fetch(file.url).then((r) => r.arrayBuffer()))
    const name = `${target.prefix}-${file.subset}.woff2`
    await writeFile(join(OUT, name), bytes)
    provenance.push(
      `${target.family} · ${file.subset} · ${name} · ${bytes.length} bytes · unicode-range: ${file.unicodeRange}`,
    )
    console.log(`${name} ${bytes.length}B`)
  }
}

await writeFile(join(OUT, 'PROVENANCE.txt'), provenance.join('\n') + '\n')
